### ISSUE TITLE
USER STORY: Matching label size to envelope type

### ISSUE THREAD

**Issue by sven-cork** [sven-cork/First-Agile-Project#2]
As an office clerk I can select various size labels to print so that the label matches the size of the envelope.

**Comment by sven-cork** [comment]
## Acceptance Criteria

- Details included with the order: Order ID, Shipping Address and list of items in the package
- Option to select between three sizes: A3, A4 and A5
- Font size is 12 points

## Tasks

- [ ] Create a print icon on website
- [ ] Design print layout for different page sizes
- [ ] Create HTML and CSS for the print icon
- [ ] Create HMTL and CSS for the different page size layouts
- [ ] Test functionality for print icon and page size selections

**Comment by sven-cork** [comment]
## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
