### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by sven-cork** [sven-cork/First-Agile-Project#4]
As a taxi dispatcher I can enter the number of passengers and location so that a car with appropriate size and proximity can bring passengers to their destination effectively.

## Acceptance criteria

- The number of passengers can be selected 
- The amount of luggate can be selected
- Passenger location and destination can be selected
- Taxis meeting passenger number and luggage criteria and within 2km of passenger location displayed

## Tasks
- [ ] Create drop menu with css/html to select number of passengers
- [ ] Create drop menu with css/html to enter number of luggare
- [ ] Create input fields with css/html to enter passenger address/post code for pickup location and destination
- [ ] Create result field with css/html to display available taxis
- [ ] Code with python available taxis to be displayed based on passenger current address and destination location and checked against database
